### ISSUE TITLE
ContratosPR Financial state - Jan. 2020

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/contratospr#1]
Añadir data financiera para el mes de Enero 2020.

**Comment by jpadilla** [comment]
This is current financials from beginning of project to end of December 2019.

| Date           | Description  | Amount       | Balance      |
|----------------|--------------|--------------|--------------|
| November 2018  | Heroku       | $    30.91   |              |
| November 2018  | Froi (Venmo) | $    (11.00) |              |
| November 2018  | José         | $    (19.91) | $    0.00    |
| December 2018  | Heroku       | $    79.16   |              |
| December 2018  | José         | $    (79.16) | $    0.00    |
| January 2019   | Heroku       | $    84.00   |              |
| January 2019   | José         | $    (84.00) | $    0.00    |
| February 2019  | Heroku       | $    39.76   |              |
| February 2019  | Froi (Venmo) | $    (50.00) | $    (10.24) |
| March 2019     | Heroku       | $    28.72   |              |
| March 2019     | José         | $    (18.48) | $    0.00    |
| April 2019     | Heroku       | $    30.00   |              |
| April 2019     | José         | $    (30.00) | $    0.00    |
| May 2019       | Heroku       | $    30.00   |              |
| May 2019       | José         | $    (30.00) | $    0.00    |
| June 2019      | Heroku       | $    30.00   |              |
| June 2019      | José         | $    (30.00) | $    0.00    |
| July 2019      | Heroku       | $    30.00   |              |
| July 2019      | José         | $    (30.00) | $    0.00    |
| August 2019    | Heroku       | $    24.65   |              |
| August 2019    | José         | $    (24.65) | $    0.00    |
| September 2019 | Heroku       | $    14.00   |              |
| September 2019 | Compose      | $    9.68    |              |
| September 2019 | José         | $    (23.68) | $    0.00    |
| October 2019   | Heroku       | $    16.26   |              |
| October 2019   | Compose      | $    41.50   |              |
| October 2019   | José         | $    (57.76) | $    0.00    |
| November 2019  | Heroku       | $    16.14   |              |
| November 2019  | Compose      | $    63.88   |              |
| November 2019  | José         | $    (80.02) | $    0.00    |
| December 2019  | Heroku       | $    14.00   |              |
| December 2019  | Compose      | $    65.50   |              |
| December 2019  | Froi (Venmo) | $    (90.00) | $    (10.50) |
|                |              |              |              |
|                |              |              |              |
|                |              |              |              |
|                |              |              |              |
|                |              |              |              |
|                |              | $    (10.50) |              |

**Comment by froi** [comment]
Thanks for doing this!!! ❤️ 

As I see it we have these totals:

### Hosting

Heroku | Compose | Grand Total
--------- | ---------- | ------------
$467.60  | $180.56     | $648.16

### Dues for each of us

648.16 / 2 = 324.08

### Contributions

José     | Froi
-------- | -------
$507.66 | $151

So, as of today Jan. 26 I owe you __$183.58__. I'll be making the transfer today. Thanks for picking this up for all this time.

**Comment by froi** [comment]
Once you add the totals for Jan. we can close this issue.

**Comment by froi** [comment]
Closing this out in favor of #3 that was created by our GH action.
